name: Android CI

on:
  push:
    branches: [main, the-basis-of-the-project, 'release/**']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build & run unit tests
        run: ./gradlew clean build --no-daemon

      - name: Run Android Lint
        run: ./gradlew lintDebug --no-daemon
